# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.dependencyVerification=off

# Mod Properties
mod_id=ifwootaddon
mod_name=Industrial Foregoing: Woot Addon
mod_version=20.1.1.2

# Platform Properties
java_version=17
mc_version=1.20.1
neo_version=47.1.106

# Dependency Properties
jei_version=15.20.0.100
jade_version=11.9.1+forge
woot_version=20.1.1.1
guideme_version=20.1.7
if_version=1.20.1-3.5.8
titanium_version=1.20.1-3.8.32

# Optimization Mods
ferritecore_version=6.0.1-forge